#!/bin/bash

csi0_test()
{
	./v4l2_test -d /dev/video0
	r=$?
	if [ "$r" -eq 0 ]; then
        	echo "Video0 OK"
#        	echo "text&csi0#ok" > ../status/s_csi
	else
        	echo "Video0 FAIL"
#        	echo "text&csi0#failed" > ../status/s_csi
        	return 2
	fi

}


csi1_test()
{
	./v4l2_test -d /dev/video1
	r=$?
	if [ "$r" -eq 0 ]; then
        	echo "Video1 OK"
#        	echo "text&csi1#ok" > ../status/s_csi
	else
        	echo "Video1 FAIL"
#        	echo "text&csi1#failed" > ../status/s_csi
        	return 3
	fi

}



echo "*************************"
echo "* CSI"
echo "*************************"

cd v4l2_test
csi0_test
r=$r
rm -rf uyvy*
if [ $r -ne 0 ]; then
	csi0_test
	r=$r
	if [ $r -ne 0 ]; then
		exit 1
	fi
fi

sleep 1

csi1_test
r=$r
rm -f uyvy*
if [ $r -ne 0 ]; then
        csi1_test
        r=$r
        if [ $r -ne 0 ]; then
                exit 1
        fi
fi

exit 0
